### ISSUE TITLE
电量统计的疑问

### ISSUE THREAD

**Issue by hqs1** [ocrobot/HLW8032#5]
我看一下手册，它是溢出会取反寄存器Bit7。取反应该是0->1 或者 1->0吧
`		// 确认 PF进位寄存器是否进位，进位则添加1
		if(bitRead(SerialTemps[20], 7) == 1)
		{
			PFData++;
		}`
但是这里1取反变0就不会自加PFDate吧

**Comment by MINI-Qiang** [comment]
很有可能，这个我还没严格测试过

**Comment by hqs1** [comment]
嗯，我问过一下合力为那边的工程师，答复是取反+1的就是0->1也是要加1

**Comment by MINI-Qiang** [comment]
帮我修下呗 囧

**Comment by hqs1** [comment]
@MINI-Qiang 行
